# Generated by Django 4.1.6 on 2023-02-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория:', 'verbose_name_plural': 'Категории:'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт:', 'verbose_name_plural': 'Продукты:'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Под категория6', 'verbose_name_plural': 'Под категории:'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='app_shop.category', verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivary',
            field=models.TextField(verbose_name='Доставка:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Изображение:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название продукта:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pay',
            field=models.TextField(verbose_name='Оплата:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(to='app_shop.subcategory', verbose_name='Под категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='teh_desc',
            field=models.TextField(verbose_name='Техническое описание:'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.category', verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Под категория:'),
        ),
    ]
