# Generated by Django 4.1.6 on 2023-02-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Под категория:', 'verbose_name_plural': 'Под категории:'},
        ),
    ]
